(function(path_to){
  script.map = {
    'object.js': path_to+'object/object.js',
    'object/chain/forEach.js': path_to+'object/chain/forEach.js',
    'object/chain/hasProperty.js': path_to+'object/chain/hasProperty.js',
    'object/chain/addEventListener.js': path_to+'object/chain/addEventListener.js',
    'object/keys.js': path_to+'object/keys.js',
    'object/type.js': path_to+'object/type.js',
    'array.js': path_to+'array/array.js',
    'chain/forEach.js': path_to+'array/chain/forEach.js',
    'chain/has.js': path_to+'array/chain/has.js',
    'chain/add.js': path_to+'array/chain/add.js',
    'chain/change.js': path_to+'array/chain/change.js',
    'chain/remove.js': path_to+'array/chain/remove.js',
    'chain/toString.js': path_to+'array/chain/toString.js',
    'chain/indexAll.js': path_to+'array/chain/indexAll.js',
    'chain/addEventListener.js': path_to+'array/chain/addEventListener.js',
    'createEvents.js': path_to+'array/createEvents.js',
    'keys.js': path_to+'array/keys.js',
  };
  script({require: [
    'object.js',
    'object/chain/forEach.js',
    'object/chain/hasProperty.js',
    'object/chain/addEventListener.js',
    'object/keys.js',
    'object/type.js',
    'array.js',
    'chain/forEach.js',
    'chain/has.js',
    'chain/add.js',
    'chain/change.js',
    'chain/remove.js',
    'chain/toString.js',
    'chain/indexAll.js',
    'chain/addEventListener.js',
    'createEvents.js',
    'keys.js',
  ]});
}(script.path.dir+'lib/js/'));
